

 db:
   image: postgres:latest
   ports:
     - "5432:5432"
   environment:
     POSTGRES_DB: ${DB_NAME}
     POSTGRES_USER: ${DB_USER}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
   volumes:
     - postgres_data:/var/lib/postgresql/data
   networks:
     - postgres

 pgadmin:
   image: dpage/pgadmin4
   restart: always
   ports:
     - "5050:80"
   environment:
     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
     PGADMIN_LISTEN_PORT: 80
   depends_on:
     - db
   networks:
     - postgres

networks:
 postgres:
   driver: bridge

volumes:
 postgres_data: